version: "3"

services:
  backend:
    env_file: "./backend/.env"
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    image: "raytangent42/tourist-souvenir-backend"
    ports:
      - "1337:1337"
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    image: "raytangent42/tourist-souvenir-frontend"
    ports:
      - "3000:3000"
    links:
      - "backend"
